<div class="content-wrapper" ng-app="app" ng-controller="productController">
    <section class="content-header">
        <script data-require="ui-bootstrap@*" data-semver="0.12.1" src="http://angular-ui.github.io/bootstrap/ui-bootstrap-tpls-0.12.1.min.js"></script>
        <h1> Manage Merchant</h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Systems setup</a></li>
            <li class="active"> Manage Merchant</li>
        </ol>
    </section>
    <section class="content container-fluid">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title"> Manage Product</h3>
                        <div class="pull-right"> 
                            &nbsp;<a href="<?php echo $this->basePath() ?>/merchant/product/getproductlist?download_csv=download_csv" class="btn btn-info"> Download Product Csv</a>
                            &nbsp;<a href="<?php echo $this->basePath() ?>/merchant/product/exportcsv" class="btn btn-info"> export Own Product</a>
                        </div>                        
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <div id="example2_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
                            <div class="row">
                                <div class="col-sm-6"></div>
                                <div class="col-sm-6"></div>
                            </div>
                            <div class="row">
                                <div class="col-sm-12">
                                    <table class="table table-bordered table-hover dataTable" id="example2" role="grid" aria-describedby="example2_info">
                                        <thead>
                                            <tr role="row">
                                                <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Rendering engine: activate to sort column ascending">Product Name</th>
                                                <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending">Category Name</th>
                                                <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending">Product Description</th>                                                
                                                <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending">Action</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr role="row" ng-repeat="(key, product) in productList">
                                                <td class="">{{product.product_name}}</td>
                                                <td class="">{{product.category_name}}</td>
                                                <td class="">{{product.product_desc}}</td>
                                                <td class="">
                                                    <div class="pull-right"> 
                                                        <a href="<?php echo $this->basePath() ?>/merchant/product/inventry?id={{product.id}}" class="btn btn-info">Manage Inventry</a>
                                                    </div>                                                    
                                                </td>
                                            </tr>
                                        </tbody>

                                    </table>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-4">
                                </div>
                                <div class="col-sm-8">
                                    <div class="dataTables_paginate paging_simple_numbers" id="example2_paginate">
                                        <pagination  class="pagination pull-right mt0" ng-model="currentPage" total-items="numberOfRecord" max-size="3" boundary-links="true" ng-click="selectPage(currentPage)"></pagination>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- /.box-body -->
                </div>
            </div>
        </div>
    </section>
</div>
<script>
    var app = angular.module('app', ['ui.bootstrap']);
</script>
<script src="<?php echo $this->basePath() . '/public/js/merchant/dashboard/product.js' ?>"></script>

