<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper" ng-app="app" ng-controller="managedashboard"  ng-cloak="true">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1> Dashboard <small>Control panel</small> </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">Dashboard</li>
        </ol>
    </section>
    <!-- Main content -->
    <section class="content container-fluid">
        <div class="box-body">
            <div class="row">
                <div class="col-md-3 col-xs-12">
                    <div class="form-group">
                        <label>Start Date</label>

                        <div class="input-group">
                            <div class="input-group-addon">
                                <i class="fa fa-calendar"></i>
                            </div>
                            <input class="datepicker" data-date-format="mm/dd/yyyy" ng-model="filter.startDate">
                        </div>
                        <!-- /.input group -->
                    </div>
                </div>                
                <div class="col-md-3 col-xs-12">
                    <div class="form-group">
                        <label>End Date</label>

                        <div class="input-group">
                            <div class="input-group-addon">
                                <i class="fa fa-calendar"></i>
                            </div>
                            <input class="datepicker" data-date-format="mm/dd/yyyy" ng-model="filter.endDate">
                        </div>
                        <!-- /.input group -->
                    </div>
                </div>
                <div class="col-md-2 col-xs-12 no-rpad"><label>&nbsp;</label>
                    <button class="btn btn-block btn-primary" type="button" ng-click="applyFilter()">Apply</button>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-8 col-md-8 col-xs-12 no-rpad">
                    <div class="box box-info">
                        <div id="container14" style="width: 100%; max-width: 850px; height: 350px; margin: 0 auto;"> </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-4 col-xs-12 ">
                    <div class="row">
                        <div class="col-lg-6 col-xs-12 no-rpad">
                            <!-- small box -->
                            <div class="small-box bg-purple">
                                <div class="inner">
                                    <h3>150</h3>
                                    <p>Total sales confirmed</p>
                                </div>
                                <div class="icon"> <i class="ion ion-bag"></i> </div>
                            </div>
                        </div>
                        <!-- ./col -->
                        <div class="col-lg-6 col-xs-12 no-rpad">
                            <!-- small box -->
                            <div class="small-box bg-olive">
                                <div class="inner">
                                    <h3>530</h3>
                                    <p>Total Order Confirmed</p>
                                </div>
                                <div class="icon"> <i class="ion ion-clipboard"></i> </div>
                            </div>
                        </div>
                        <div class="col-lg-6 col-xs-12 no-rpad">
                            <!-- small box -->
                            <div class="small-box bg-red">
                                <div class="inner">
                                    <h3>530</h3>
                                    <p>No of Active Customer</p>
                                </div>
                                <div class="icon"> <i class="fa fa-users"></i> </div>
                            </div>
                        </div>
                        <div class="col-lg-6 col-xs-12 no-rpad">
                            <!-- small box -->
                            <div class="small-box bg-yellow">
                                <div class="inner">
                                    <h3>530</h3>
                                    <p>No of product added</p>
                                </div>
                                <div class="icon"> <i class="fa fa-dropbox"></i> </div>
                            </div>
                        </div>
                        <!-- ./col -->
                        <div class="col-lg-12 col-xs-12 no-rpad">
                            <!-- small box -->
                            <div class="small-box bg-bllue-dark">
                                <div class="inner">
                                    <h3>44</h3>
                                    <p>No of Merchant Added</p>
                                </div>
                                <div class="icon"> <i class="fa fa-bank"></i> </div>
                            </div>
                        </div>
                        <!-- ./col -->
                    </div>
                </div>
            </div>
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->
<!-- Main Footer -->
<!-- Control Sidebar -->
<!-- /.control-sidebar -->
<!-- Add the sidebar's background. This div must be placed
immediately after the control sidebar -->

<div class="control-sidebar-bg"></div>
<!-- Optionally, you can add Slimscroll and FastClick plugins.
     Both of these plugins are recommended to enhance the
     user experience. -->
<script type="text/javascript" src="<?=$this->basePath()?>/public/js/highcharts.js"></script>
<script type="text/javascript" src="<?=$this->basePath()?>/public/js/exporting.js"></script>
<script type="text/javascript" src="<?=$this->basePath()?>/public/js/waypoints.js"></script>
<script>
    $(function () {
        $('.datepicker').datepicker();
    });
</script>
<script type='text/javascript'>
    $(function () {
        $('#container14').highcharts({
            title: {
                text: 'Order Status',
                x: -30 //center
            },
            subtitle: {
                text: '',
                x: -30
            },
            xAxis: {
                categories: ['1 Jan 17 - 2 Jan 17', '1/02/2017', '1/03/2017', '1/04/2017', '1/05/2017', '1/06/2017',
                    '1/07/2017', '1/08/2017', '1/08/2017', '1/09/2017', '1/10/2017', '1/11/2017', '1/12/2017']
            },
            yAxis: {
                title: {
                    text: 'No Of Order'
                },
                plotLines: [{
                        value: 0,
                        width: 1,
                        color: '#808080'
                    }]
            },
            tooltip: {
                valueSuffix: ''
            },
            legend: {
                layout: 'vertical',
                align: 'right',
                verticalAlign: 'middle',
                borderWidth: 0
            },
            series: [{
                    name: 'No of Confirmed Order',
                    data: [7.0, 10.9, 14.5, 18.5, 22.2, 25.5, 29.2, 32.5, 86.3, 42.3, 48.9, 54.6]
                }, {
                    name: 'Confirmed Order Amount',
                    data: [10.2, 10.8, 15.7, 21.3, 27.0, 32.0, 34.8, 44.1, 70.1, 44.1, 50.6, 50]
                }, {
                    name: 'No of Cancelled Order',
                    data: [10.9, 20.6, 23.5, 28.4, 33.5, 37.0, 48.6, 57.9, 64.3, 90.0, 60.9, 75.0]
                }, {
                    name: 'Cancelled Order Amount',
                    data: [13.9, 54.2, 45.7, 38.5, 81.9, 85.2, 77.0, 66.6, 54.2, 50.3, 60.6, 40.8]
                }]
        });
    });
</script> 
<script src="<?php echo $this->basePath() . '/public/js/dashboard/dashboard.js' ?>">
</script>