<!--<div class="content-wrapper">
<section class="content-header">
      <h1> Manage Merchant</h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Systems setup</a></li>
        <li class="active"> Manage Merchant</li>
      </ol>
    </section>
<section class="content container-fluid">
      <div class="row">
        <div class="col-xs-12">
          <div class="box">
            <div class="box-header">
              <h3 class="box-title"> Manage Merchant</h3>
              <div class="pull-right"> 
                  <a href="<?php echo $this->basePath()?>/admin/dashboard/editmerchant" class="btn btn-info"> Add Merchant</a>
              </div> 
            </div>
             /.box-header 
            <div class="box-body">
                <p class="danger showMsg" style="color:green">
                    <?php
                        if(!empty($this->flashMessenger()->getMessages())){
                            $msg =  $this->flashMessenger()->getMessages();
                            echo $msg[0];
                        }
                    ?>                         
                </p>                
              <div id="example2_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
                <div class="row">
                  <div class="col-sm-6"></div>
                  <div class="col-sm-6"></div>
                </div>
                <div class="row">
                  <div class="col-sm-12">
                    <table class="table table-bordered table-hover dataTable" id="example2" role="grid" aria-describedby="example2_info">
                      <thead>
                        <tr role="row">
                          <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Rendering engine: activate to sort column ascending">Onwer name</th>
                          <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Browser: activate to sort column ascending">IC Number</th>
                          <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Platform(s): activate to sort column ascending">Phone Numbmer</th>
                          <th class="sorting_desc" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Engine version: activate to sort column ascending" aria-sort="descending">Email</th>
                          <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending">Address</th>
						  <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending">Company Bank name</th>
						  <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending">Company Bank Account Number</th>
						  <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending">Action</th>
                        </tr>
                      </thead>
                      <tbody>
                          <?php if(!empty($this->marchantList)){
                            foreach ($this->marchantList as $key => $value) {
                              ?>
                            <tr role="row" class="odd">
                            <td class=""><?php if($value['status'] == 0) {?><i class="fa fa-close red"></i> &nbsp;<?php }?><?= $value['first_name']?></td>
                              <td class=""><?= $value['ic_number']?></td>
                              <td class=""><?= $value['phone_number']?></td>
                              <td class="sorting_1"><?= $value['email']?></td>
                              <td><?= $value['address']?></td>
                              <td><?= $value['bank_name']?></td>
                              <td><?= $value['bank_account_number']?></td>
                              <td><a href="editmerchant?id=<?= $value['user_id']?>"><i class="fa fa-edit"></i> 
                                  <i class="fa fa-trash-o"></i></a></td>
                            </tr>
                          <?php }}?>
                      </tbody>
                      
                    </table>
                  </div>
                </div>
                <div class="row">
                  <div class="col-sm-4">
                    <div class="dataTables_info" id="example2_info" role="status" aria-live="polite">Showing <?= count($this->marchantList)?> entries</div>
                  </div>
                  <div class="col-sm-8">
                    <div class="dataTables_paginate paging_simple_numbers" id="example2_paginate">
                      <ul class="pagination pull-right mt0">
                        <li class="paginate_button previous disabled" id="example2_previous"><a href="#" aria-controls="example2" data-dt-idx="0" tabindex="0">Previous</a></li>
                        <li class="paginate_button active"><a href="#" aria-controls="example2" data-dt-idx="1" tabindex="0">1</a></li>
                        <li class="paginate_button "><a href="#" aria-controls="example2" data-dt-idx="2" tabindex="0">2</a></li>
                        <li class="paginate_button "><a href="#" aria-controls="example2" data-dt-idx="3" tabindex="0">3</a></li>
                        <li class="paginate_button "><a href="#" aria-controls="example2" data-dt-idx="4" tabindex="0">4</a></li>
                        <li class="paginate_button "><a href="#" aria-controls="example2" data-dt-idx="5" tabindex="0">5</a></li>
                        <li class="paginate_button "><a href="#" aria-controls="example2" data-dt-idx="6" tabindex="0">6</a></li>
                        <li class="paginate_button next" id="example2_next"><a href="#" aria-controls="example2" data-dt-idx="7" tabindex="0">Next</a></li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
             /.box-body 
          </div>
        </div>
      </div>
    </section>
</div>
-->



<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title>AFRO BASKETS</title>
<!-- Tell the browser to be responsive to screen width -->
<meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
<link rel="stylesheet" href="bower_components/bootstrap/dist/css/bootstrap.min.css">
<!-- Font Awesome -->
<link rel="stylesheet" href="bower_components/font-awesome/css/font-awesome.min.css">
<!-- Ionicons -->
<link rel="stylesheet" href="bower_components/Ionicons/css/ionicons.min.css">
<!-- daterange picker -->
<link rel="stylesheet" href="bower_components/bootstrap-daterangepicker/daterangepicker.css">
<!-- bootstrap datepicker -->
<link rel="stylesheet" href="bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css">
<!-- Select2 -->
<link rel="stylesheet" href="bower_components/select2/dist/css/select2.min.css">
<!-- Theme style -->
<link rel="stylesheet" href="dist/css/style.css">
<!-- AdminLTE Skins. We have chosen the skin-blue for this starter
        page. However, you can choose any other skin. Make sure you
        apply the skin class to the body tag so the changes take effect. -->
<link rel="stylesheet" href="dist/css/skins/skin-blue.min.css">
<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
<!-- Google Font -->
<link rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<!--
BODY TAG OPTIONS:
=================
Apply one or more of the following classes to get the
desired effect
|---------------------------------------------------------|
| SKINS         | skin-blue                               |
|               | skin-black                              |
|               | skin-purple                             |
|               | skin-yellow                             |
|               | skin-red                                |
|               | skin-green                              |
|---------------------------------------------------------|
|LAYOUT OPTIONS | fixed                                   |
|               | layout-boxed                            |
|               | layout-top-nav                          |
|               | sidebar-collapse                        |
|               | sidebar-mini                            |
|---------------------------------------------------------|
-->
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">
  <!-- Main Header -->
  <header class="main-header">
    <!-- Logo -->
    <a href="index2.html" class="logo">
    <!-- mini logo for sidebar mini 50x50 pixels -->
    <span class="logo-mini"><img src="dist/img/logo-mini.png" class="" alt="Logo"></span>
    <!-- logo for regular state and mobile devices -->
    <span class="logo-lg"><img src="dist/img/logo.png" class="" alt="Logo"></span> </a>
    <!-- Header Navbar -->
    <nav class="navbar navbar-static-top" role="navigation">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button"> <span class="sr-only">Toggle navigation</span> </a>
      <!-- Navbar Right Menu -->
      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
          <!-- Messages: style can be found in dropdown.less-->
          <li class="dropdown messages-menu">
            <!-- Menu toggle button -->
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <i class="fa fa-envelope-o"></i> <span class="label label-success">4</span> </a>
            <ul class="dropdown-menu">
              <li class="header">You have 4 messages</li>
              <li>
                <!-- inner menu: contains the messages -->
                <ul class="menu">
                  <li>
                    <!-- start message -->
                    <a href="#">
                    <div class="pull-left">
                      <!-- User Image -->
                      <img src="dist/img/avatar04.png" class="img-circle" alt="User Image"> </div>
                    <!-- Message title and timestamp -->
                    <h4> Support Team <small><i class="fa fa-clock-o"></i> 5 mins</small> </h4>
                    <!-- The message -->
                    <p>Why not buy a new awesome theme?</p>
                    </a> </li>
                  <!-- end message -->
                </ul>
                <!-- /.menu -->
              </li>
              <li class="footer"><a href="#">See All Messages</a></li>
            </ul>
          </li>
          <!-- /.messages-menu -->
          <!-- Notifications Menu -->
          <li class="dropdown notifications-menu">
            <!-- Menu toggle button -->
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <i class="fa fa-bell-o"></i> <span class="label label-warning">10</span> </a>
            <ul class="dropdown-menu">
              <li class="header">You have 10 notifications</li>
              <li>
                <!-- Inner Menu: contains the notifications -->
                <ul class="menu">
                  <li>
                    <!-- start notification -->
                    <a href="#"> <i class="fa fa-users text-aqua"></i> 5 new members joined today </a> </li>
                  <!-- end notification -->
                </ul>
              </li>
              <li class="footer"><a href="#">View all</a></li>
            </ul>
          </li>
          <!-- Tasks Menu -->
          <li class="dropdown tasks-menu">
            <!-- Menu Toggle Button -->
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <i class="fa fa-flag-o"></i> <span class="label label-danger">9</span> </a>
            <ul class="dropdown-menu">
              <li class="header">You have 9 tasks</li>
              <li>
                <!-- Inner menu: contains the tasks -->
                <ul class="menu">
                  <li>
                    <!-- Task item -->
                    <a href="#">
                    <!-- Task title and progress text -->
                    <h3> Design some buttons <small class="pull-right">20%</small> </h3>
                    <!-- The progress bar -->
                    <div class="progress xs">
                      <!-- Change the css width attribute to simulate progress -->
                      <div class="progress-bar progress-bar-aqua" style="width: 20%" role="progressbar"
                             aria-valuenow="20" aria-valuemin="0" aria-valuemax="100"> <span class="sr-only">20% Complete</span> </div>
                    </div>
                    </a> </li>
                  <!-- end task item -->
                </ul>
              </li>
              <li class="footer"> <a href="#">View all tasks</a> </li>
            </ul>
          </li>
          <!-- User Account Menu -->
          <li class="dropdown user user-menu">
            <!-- Menu Toggle Button -->
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <!-- The user image in the navbar-->
            <img src="dist/img/avatar04.png" class="user-image" alt="User Image">
            <!-- hidden-xs hides the username on small devices so only the image appears. -->
            <span class="hidden-xs">Rakesh Tiwari</span> </a>
            <ul class="dropdown-menu">
              <!-- The user image in the menu -->
              <li class="user-header"> <img src="dist/img/avatar04.png" class="img-circle" alt="User Image">
                <p> Rakesh - Web Developer <small>Member since Nov. 2017</small> </p>
              </li>
              <!-- Menu Body -->
              <li class="user-body">
                <div class="row">
                  <div class="col-xs-4 text-center"> <a href="#">Followers</a> </div>
                  <div class="col-xs-4 text-center"> <a href="#">Sales</a> </div>
                  <div class="col-xs-4 text-center"> <a href="#">Friends</a> </div>
                </div>
                <!-- /.row -->
              </li>
              <!-- Menu Footer-->
              <li class="user-footer">
                <div class="pull-left"> <a href="#" class="btn btn-default btn-flat">Profile</a> </div>
                <div class="pull-right"> <a href="#" class="btn btn-default btn-flat">Sign out</a> </div>
              </li>
            </ul>
          </li>
          <!-- Control Sidebar Toggle Button -->
          <li class="hide"> <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a> </li>
        </ul>
      </div>
    </nav>
  </header>
  <!-- Left side column. contains the logo and sidebar -->
  <aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
      <!-- Sidebar Menu -->
      <ul class="sidebar-menu" data-widget="tree">
        <li  class="active"><a href="#"><i class="fa fa-tachometer"></i> <span>Dashboard</span></a></li>
        <!-- Optionally, you can add icons to the links -->
        <li><a href="#"><i class="fa fa-sitemap"></i> <span>Manage Category</span></a></li>
        <li><a href="#"><i class="fa fa-suitcase"></i> <span>Manage Product</span></a></li>
        <li><a href="#"><i class="fa fa-motorcycle"></i> <span>Manage Riders</span></a></li>
        <li class="treeview"> <a href="#"><i class="fa fa-link"></i> <span>System Setup</span> <span class="pull-right-container"> <i class="fa fa-angle-left pull-right"></i> </span> </a>
          <ul class="treeview-menu">
            <li><a href="#"><i class="fa fa-file-o"></i> <span>Manage Tax</span></a></li>
            <li><a href="#"><i class="fa fa-file-text"></i> <span>Manage Orders</span></a></li>
            <li><a href="manage-merchant.html"><i class="fa fa-users"></i> <span>Manage Merchant</span></a></li>
          </ul>
        </li>
      </ul>
      <!-- /.sidebar-menu -->
    </section>
    <!-- /.sidebar -->
  </aside>
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1> Manage Merchant</h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Systems setup</a></li>
        <li class="active"> Manage Merchant</li>
      </ol>
    </section>
    <!-- Main content -->
    <section class="content container-fluid">
      <div class="row">
        <div class="col-xs-12">
          <div class="box">
            <div class="box-header">
              <h3 class="box-title"> Manage Merchant</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
			<div class="row">
			<div class="col-sm-10 col-lg-10  no-rpad">
			<label class="ml10">Search By</label></div>
                  <div class="col-sm-10 col-lg-10  no-rpad">
				  <div class="input-group margin mt0">				  
                <div class="input-group-btn">
                  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">Action
                    <span class="fa fa-caret-down"></span></button>
                  <ul class="dropdown-menu">
                    <li><a href="#">Name</a></li>
                    <li><a href="#">Email</a></li>
                    <li><a href="#">Number</a></li> 
                  </ul>
                </div>
                <!-- /btn-group -->
                <input type="text" class="form-control">
              </div>
				  </div>
                  <div class="col-sm-2 no-lpad">
				  <button class="btn btn-default pull-right" type="button" id="show-attribute"><i class="fa fa-align-left"></i> Search Filter</button>
				  </div>
				  <div class=" col-lg-12" id="add-attribute" style="display:none;">
                      <div class="full-width pull-left">
                        <div class="col-lg-5 col-sm-6 col-xs-12 mt10">
                          <div class="form-group">
                            <label>Company Bank name</label>
                            <select class="form-control select2" style="width: 100%;">
                              <option selected="selected">ICICI Bank</option>
                              <option>HDFC Bank</option>
                              <option>SBI Bank</option>
                              <option>PNB Bank</option>
                            </select>
                          </div>
                        </div>
                        <div class="col-lg-5 col-sm-6 col-xs-12 mt10">
                           <div class="form-group">
                            <label>Company Bank name</label>
                            <select class="form-control select2" style="width: 100%;">
                              <option selected="selected">ICICI Bank</option>
                              <option>HDFC Bank</option>
                              <option>SBI Bank</option>
                              <option>PNB Bank</option>
                            </select>
                          </div>
                        </div>
						<div class="col-lg-2 col-sm-6 col-xs-12 mt10">
                          <div class="form-group">
                            <label>&nbsp;</label>
                            <button class="btn btn-block btn-primary" type="button">Save</button>
                          </div>
						</div>
                      </div>
                      <div class="full-width pull-left border-top">&nbsp;</div>
                    </div>
                    <div class="clearfix"></div>
                    
					
                </div>
              <div id="example2_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
                <div class="row">
                  <div class="col-sm-6"></div>
                  <div class="col-sm-6"></div>
                </div>
                <div class="row">
                  <div class="col-sm-12">
                    <table class="table table-bordered table-hover dataTable" id="example2" role="grid" aria-describedby="example2_info">
                      <thead>
                        <tr role="row">
                          <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Rendering engine: activate to sort column ascending">Onwer name</th>
                          <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Browser: activate to sort column ascending">IC Number</th>
                          <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Platform(s): activate to sort column ascending">Phone Numbmer</th>
                          <th class="sorting_desc" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Engine version: activate to sort column ascending" aria-sort="descending">Email</th>
                          <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending">Address</th>
						  <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending">Company Bank name</th>
						  <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending">Company Bank Account Number</th>
						  <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending">Action</th>
                        </tr>
                      </thead>
                      <tbody>
                        <tr role="row" class="odd">
                          <td class="">Webkit</td>
                          <td class="">Safari 3.0</td>
                          <td class="">OSX.4+</td>
                          <td class="sorting_1">522.1</td>
                          <td>A</td>
						  <td>ICICI</td>
						  <td>000000</td>
						  <td><a href="#"><i class="fa fa-edit"></i> <i class="fa fa-trash-o"></i></a></td>
                        </tr>
                        <tr role="row" class="even">
                          <td class="">Webkit</td>
                          <td class="">iPod Touch / iPhone</td>
                          <td class="">iPod</td>
                          <td class="sorting_1">420.1</td>
                          <td>A</td>
						  <td>ICICI</td>
						  <td>000000</td>
						  <td><a href="#"><i class="fa fa-edit"></i> <i class="fa fa-trash-o"></i></a></td>
                        </tr>
                        <tr role="row" class="odd">
                          <td class="">Webkit</td>
                          <td class="">OmniWeb 5.5</td>
                          <td class="">OSX.4+</td>
                          <td class="sorting_1">420</td>
                          <td>A</td>
						  <td>ICICI</td>
						  <td>000000</td>
						  <td><a href="#"><i class="fa fa-edit"></i> <i class="fa fa-trash-o"></i></a></td>
                        </tr>
                        <tr role="row" class="even">
                          <td class="">Webkit</td>
                          <td class="">Safari 2.0</td>
                          <td class="">OSX.4+</td>
                          <td class="sorting_1">419.3</td>
                          <td>A</td>
						  <td>ICICI</td>
						  <td>000000</td>
						  <td><a href="#"><i class="fa fa-edit"></i> <i class="fa fa-trash-o"></i></a></td>
                        </tr>
                        <tr role="row" class="odd">
                          <td class="">Webkit</td>
                          <td class="">S60</td>
                          <td class="">S60</td>
                          <td class="sorting_1">413</td>
                          <td>A</td>
						  <td>ICICI</td>
						  <td>000000</td>
						  <td><a href="#"><i class="fa fa-edit"></i> <i class="fa fa-trash-o"></i></a></td>
                        </tr>
                        <tr role="row" class="even">
                          <td class="">Webkit</td>
                          <td class="">Safari 1.3</td>
                          <td class="">OSX.3</td>
                          <td class="sorting_1">312.8</td>
                          <td>A</td>
						  <td>ICICI</td>
						  <td>000000</td>
						  <td><a href="#"><i class="fa fa-edit"></i> <i class="fa fa-trash-o"></i></a></td>
                        </tr>
                        <tr role="row" class="odd">
                          <td class="">Webkit</td>
                          <td class="">Safari 1.2</td>
                          <td class="">OSX.3</td>
                          <td class="sorting_1">125.5</td>
                          <td>A</td>
						  <td>ICICI</td>
						  <td>000000</td>
						  <td><a href="#"><i class="fa fa-edit"></i> <i class="fa fa-trash-o"></i></a></td>
                        </tr>
                        <tr role="row" class="even">
                          <td class="">Presto</td>
                          <td class="">Nintendo DS browser</td>
                          <td class="">Nintendo DS</td>
                          <td class="sorting_1">8.5</td>
                          <td>C/A<sup>1</sup></td>
						  <td>ICICI</td>
						  <td>000000</td>
						  <td><a href="#"><i class="fa fa-edit"></i> <i class="fa fa-trash-o"></i></a></td>
                        </tr>
                        <tr role="row" class="odd">
                          <td class="">Trident</td>
                          <td class="">Internet Explorer 7</td>
                          <td class="">Win XP SP2+</td>
                          <td class="sorting_1">7</td>
                          <td>A</td>
						  <td>ICICI</td>
						  <td>000000</td>
						  <td><a href="#"><i class="fa fa-edit"></i> <i class="fa fa-trash-o"></i></a></td>
                        </tr>
                        <tr role="row" class="even">
                          <td class="">Trident</td>
                          <td class="">AOL browser (AOL desktop)</td>
                          <td class="">Win XP</td>
                          <td class="sorting_1">6</td>
                          <td>A</td>
						  <td>ICICI</td>
						  <td>000000</td>
						  <td><a href="#"><i class="fa fa-edit"></i> <i class="fa fa-trash-o"></i></a></td>
                        </tr>
                      </tbody>
                      
                    </table>
                  </div>
                </div>
                <div class="row">
                  <div class="col-sm-4">
                    <div class="dataTables_info" id="example2_info" role="status" aria-live="polite">Showing 1 to 10 of 57 entries</div>
                  </div>
                  <div class="col-sm-8">
                    <div class="dataTables_paginate paging_simple_numbers" id="example2_paginate">
                      <ul class="pagination pull-right mt0">
                        <li class="paginate_button previous disabled" id="example2_previous"><a href="#" aria-controls="example2" data-dt-idx="0" tabindex="0">Previous</a></li>
                        <li class="paginate_button active"><a href="#" aria-controls="example2" data-dt-idx="1" tabindex="0">1</a></li>
                        <li class="paginate_button "><a href="#" aria-controls="example2" data-dt-idx="2" tabindex="0">2</a></li>
                        <li class="paginate_button "><a href="#" aria-controls="example2" data-dt-idx="3" tabindex="0">3</a></li>
                        <li class="paginate_button "><a href="#" aria-controls="example2" data-dt-idx="4" tabindex="0">4</a></li>
                        <li class="paginate_button "><a href="#" aria-controls="example2" data-dt-idx="5" tabindex="0">5</a></li>
                        <li class="paginate_button "><a href="#" aria-controls="example2" data-dt-idx="6" tabindex="0">6</a></li>
                        <li class="paginate_button next" id="example2_next"><a href="#" aria-controls="example2" data-dt-idx="7" tabindex="0">Next</a></li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <!-- /.box-body -->
          </div>
        </div>
      </div>
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
  <!-- Main Footer -->
  <footer class="main-footer">
    <!-- To the right -->
    <div class="pull-right hidden-xs"> DESIGNED BY: DESIGNER RAKESH </div>
    <!-- Default to the left -->
    <strong>Copyright &copy; 2017 <a href="#">AFRABASKET</a>.</strong> All rights reserved. </footer>
  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark hide">
    <!-- Create the tabs -->
    <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
      <li class="active"><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
      <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
    </ul>
    <!-- Tab panes -->
    <div class="tab-content">
      <!-- Home tab content -->
      <div class="tab-pane active" id="control-sidebar-home-tab">
        <h3 class="control-sidebar-heading">Recent Activity</h3>
        <ul class="control-sidebar-menu">
          <li> <a href="javascript:;"> <i class="menu-icon fa fa-birthday-cake bg-red"></i>
            <div class="menu-info">
              <h4 class="control-sidebar-subheading">Langdon's Birthday</h4>
              <p>Will be 23 on April 24th</p>
            </div>
            </a> </li>
        </ul>
        <!-- /.control-sidebar-menu -->
        <h3 class="control-sidebar-heading">Tasks Progress</h3>
        <ul class="control-sidebar-menu">
          <li> <a href="javascript:;">
            <h4 class="control-sidebar-subheading"> Custom Template Design <span class="pull-right-container"> <span class="label label-danger pull-right">70%</span> </span> </h4>
            <div class="progress progress-xxs">
              <div class="progress-bar progress-bar-danger" style="width: 70%"></div>
            </div>
            </a> </li>
        </ul>
        <!-- /.control-sidebar-menu -->
      </div>
      <!-- /.tab-pane -->
      <!-- Stats tab content -->
      <div class="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div>
      <!-- /.tab-pane -->
      <!-- Settings tab content -->
      <div class="tab-pane" id="control-sidebar-settings-tab">
        <form method="post">
          <h3 class="control-sidebar-heading">General Settings</h3>
          <div class="form-group">
            <label class="control-sidebar-subheading"> Report panel usage
            <input type="checkbox" class="pull-right" checked>
            </label>
            <p> Some information about this general settings option </p>
          </div>
          <!-- /.form-group -->
        </form>
      </div>
      <!-- /.tab-pane -->
    </div>
  </aside>
  <!-- /.control-sidebar -->
  <!-- Add the sidebar's background. This div must be placed
  immediately after the control sidebar -->
  <div class="control-sidebar-bg"></div>
</div>
<!-- ./wrapper -->
<!-- REQUIRED JS SCRIPTS -->
<!-- jQuery 3 -->
<script src="bower_components/jquery/dist/jquery.min.js"></script>
<!-- Bootstrap 3.3.7 -->
<script src="bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
<!-- Select2 -->
<script src="bower_components/select2/dist/js/select2.full.min.js"></script>
<!-- date-range-picker -->
<script src="bower_components/moment/min/moment.min.js"></script>
<script src="bower_components/bootstrap-daterangepicker/daterangepicker.js"></script>
<!-- bootstrap datepicker -->
<script src="bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>
<!-- SlimScroll -->
<script src="bower_components/jquery-slimscroll/jquery.slimscroll.min.js"></script>
<!-- AdminLTE App -->
<script src="dist/js/adminlte.min.js"></script>

<!-- Optionally, you can add Slimscroll and FastClick plugins.
     Both of these plugins are recommended to enhance the
     user experience. -->
<script type="text/javascript" src="js/highcharts.js"></script>
<script type="text/javascript" src="js/exporting.js"></script>
<script type="text/javascript" src="js/waypoints.js"></script>



</body>
</html>

