<div class="content-wrapper"  ng-app="product" ng-controller="productController">
    <section class="content-header">
        <h1> Add Product</h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Manage Product</a></li>
            <li class="active"> Add Product</li>
        </ol>
    </section>
    <!-- Main content -->
    <section class="content container-fluid">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
            <!-- /.box-header -->
                    <div class="box-body">
                        <div class="row">
                            <div class="col-lg-4 col-sm-4 col-xs-12">
                                <div class="box-header">
                                    <h3 class="box-title"> Add Product</h3>
                                    <p>Lorem ipsum is a dummy text</p>
                                </div>
                            </div>
                            <div class="col-lg-8 col-sm-8 col-xs-12">
                                <div class="row">
                                    <div class="col-lg-6 col-sm-6 col-xs-12">
                                        <div class="form-group">
                                            <label>Product Name</label>
                                            <input type="text" placeholder="Product Name" class="form-control">
                                        </div>
                                    </div>
                                    <div class="col-lg-6 col-sm-6 col-xs-12">
                                        <div class="form-group">
                                            <label>Category</label>
                                            <select class="form-control select2" style="width: 100%;">
                                                <option selected="selected" value="">Select Category</option>
                                                <option ng-repeat="data in categoryList" value="{{data.id}}">{{data.category_name}}</option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-lg-6 col-sm-6 col-xs-12">
                                        <div class="form-group">
                                            <label>Product Display</label>
                                            <div class="input-group date">
                                                <input type="text" id="datepicker" class="form-control pull-right">
                                                <div class="input-group-addon"> <i class="fa fa-calendar"></i> </div>
                                            </div>
                        <!-- /.input group -->
                                        </div>
                                    </div>
                                    <div class="col-lg-6 col-sm-6 col-xs-12">
                                        <label>&nbsp; &nbsp;</label>
                                        <div class="clearfix"></div>  
                                        <button class="btn btn-default" type="button" id="show-attribute" ng-click="showAttrDiv()"><i class="fa fa-plus"></i> Add Attribute</button>
                                    </div>
                                    <div class="clearfix"></div>
                                    <div id="add-attribute" ng-show="showAttr">
                                        <div class="col-lg-6 col-sm-6 col-xs-12">
                                            <div class="form-group">
                                                <label>Attribute Name</label>
                                                <input type="text" placeholder="Attribute Name" class="form-control">
                                            </div>
                                        </div>
                                        <div class="col-lg-6 col-sm-6 col-xs-12">
                                            <div class="form-group">
                                                <label>Unit</label>
                                                <select class="form-control select2" style="width: 100%;">
                                                    <option selected="selected">1</option>
                                                    <option>2</option>
                                                    <option>3</option>
                                                    <option>4</option>
                                                </select>
                                            </div>
                                        </div>
                                        <div class="col-lg-6 col-sm-6 col-xs-12">
                                            <div class="form-group">
                                                <label>Quantity</label>
                                                <input type="text" placeholder="Quantity" class="form-control">
                                            </div>
                                        </div>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="box-footer">
                        <div class="pull-right">
                            <button class="btn btn-default mr10" type="submit">Cancel</button>
                            <button class="btn btn-info" type="submit" ng-click="saveproduct">Save</button>
                        </div>
                    </div>
            <!-- /.box-body -->
                </div>
            </div>
        </div>
    </section>
    <!-- /.content -->
</div>
<script src="<?php echo $this->basePath() . '/public/js/dashboard/addproduct.js' ?>">
</script>

